const ENDPOINT = "https://ap-portfolio-backend.up.railway.app/";
const PORT_TOKEN = "PORTFOLIO_TOKEN";
const PORT_USER = "PORTFOLIO_USER";
const SKILLS_LIMIT = 10;
const EDUCATIONS_LIMIT = 10;
const PORTFOLIOS_LIMIT = 10;
const USERS_LIMIT = 10;
const EXPERIENCES_LIMIT = 10;

export {
  ENDPOINT,
  PORT_TOKEN,
  PORT_USER,
  SKILLS_LIMIT,
  EDUCATIONS_LIMIT,
  PORTFOLIOS_LIMIT,
  USERS_LIMIT,
  EXPERIENCES_LIMIT,
};
